server.address: 127.0.0.1
server.port: 1888
server:
  servlet:
    context-path: /test-api

spring:
  application.name: asmkt-api-test
  cloud:
    nacos.discovery.server-addr: 127.0.0.1:8848
    nacos.discovery.ip: 127.0.0.1

#最大连接数
http:
  maxTotal: 1000
#并发数
  defaultMaxPerRoute: 20000
#创建连接的最长时间
  connectTimeout: 100000
#从连接池中获取到连接的最长时间
  connectionRequestTimeout: 50000
#数据传输的最长时间
  socketTimeout: 10000
#提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true

ribbon.ConnectTimeout: 500000
ribbon.ReadTimeout: 500000

logging:
  level:
    root: info